# Site settings
title: 陋 室
header-img: img/home-bg.jpg
email: xbmdzkk@163.com 
copyright_name: Your/Project/Corporate Name
description: "孔子云：何陋之有？"
baseurl: ""
url: "https://baikongkong.github.io"
twitter_username: 
github_username: Baikongkong 
facebook_username:  
email_username:  

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
